ansys/python-installer-qt-gui

src/ansys/tools/installer/constants.py
src/ansys/tools/installer/create_virtual_environment.py
src/ansys/tools/installer/main.py
src/ansys/tools/installer/misc.py

feat: include PyAnsys docs section

---

.github/workflows/ci_cd.yml
README.rst
doc/make.bat
doc/source/index.rst
src/ansys/tools/installer/auto_updater.py
tests/test_auto_updater.py

feat: enable pre-commit.ci and add badges

---

.pre-commit-config.yaml
Makefile
make.bat
pyproject.toml
src/ansys/tools/installer/common.py
src/ansys/tools/installer/constants.py
src/ansys/tools/installer/find_python.py
src/ansys/tools/installer/installed_table.py
src/ansys/tools/installer/main.py

Resolve #86 by adding support for linux.
Also, resolve #87 by reducing the reliance on an external connection to PyPI when starting the application.

Add linux support

---

src/ansys/tools/installer/main.py

feat: fallback method for Windows without requests lib

---

README.rst
SECURITY.md

Adding SECURITY.md

---

.github/workflows/ci_cd.yml

cicd: change signtool repo location

---

AUTHORS.md
frozen.spec

As title says. Thanks @kmahajan-cadfem for all your contributions!

feat: adding kmahajan-cadfem as contributor + missing metadata

---

src/ansys/tools/installer/find_python.py

fix: issue with Ansys Python installs

---

.github/workflows/ci_cd.yml

feat: allow unsigned exe

---

src/ansys/tools/installer/common.py
src/ansys/tools/installer/main.py

added one more exception `requests.exceptions.ConnectionErrorr` so that user can open UI, even without any internet connection

open ui even if someone is offline

---

src/ansys/tools/installer/main.py

feat: update versions for miniforge and Python 3.11

---

.pre-commit-config.yaml
src/ansys/tools/installer/__init__.py
src/ansys/tools/installer/__main__.py
src/ansys/tools/installer/auto_updater.py
src/ansys/tools/installer/common.py
src/ansys/tools/installer/constants.py
src/ansys/tools/installer/create_virtual_environment.py
src/ansys/tools/installer/find_python.py
src/ansys/tools/installer/installed_table.py
src/ansys/tools/installer/installer.py
src/ansys/tools/installer/main.py
src/ansys/tools/installer/misc.py
src/ansys/tools/installer/progress_bar.py
tests/test_auto_updater.py
tests/test_gui.py
tests/test_metadata.py

feat: add license headers

---

Makefile
make.bat
src/ansys/tools/installer/linux_functions.py

feat: updating makefiles

---

.github/workflows/autoupdate_python_versions.yml
scripts/update_python_versions.py
src/ansys/tools/installer/constants.py
src/ansys/tools/installer/main.py

feat: autoupdate Python versions

---

src/ansys/tools/installer/constants.py

This PR updates the Python versions in the CI configuration files.

chore: update Python versions

---

.github/workflows/ci_cd.yml

enable fail-fast: false on Linx build stages

---

.github/workflows/autoupdate_python_versions.yml

fix: use action to perform autoupdate

---

.github/workflows/ci_cd.yml

Linux build fix

---

src/ansys/tools/installer/main.py

fix: no decoding necessary

---

src/ansys/tools/installer/constants.py

I just saw the proposition of modification of Maxime in the toolkit PR. I'm adding it here too.

docs: fix typo in about message

---

.github/workflows/ci_cd.yml

tmp: ignore artifact upload

---

.github/workflows/ci_cd.yml

fix: signtool

---

.github/workflows/ci_cd.yml

As title says - coming from https://github.com/actions/runner-images/issues/11101

ci: remove usage of 20.04 ubuntu runner
